name: update-contributors-graphic

on:
  schedule:
    # Monthly
    - cron: 0 0 1 * *

jobs:
  UpdateGraphic:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Cache Data
      id: cache-data
      uses: actions/cache@v1
      with:
        path: sourcecred_data
        key: ${{ runner.os }}-sourcecred_data
    - name: Build the Docker image
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p sourcecred_data
        SOURCECRED_GITHUB_TOKEN=${TOKEN} docker run -i -v $PWD/sourcecred_data:/data -e SOURCECRED_GITHUB_TOKEN sourcecred/sourcecred:dev load ${GITHUB_REPOSITORY}
        SOURCECRED_GITHUB_TOKEN=${TOKEN} docker run -i -v $PWD/sourcecred_data:/data sourcecred/sourcecred:dev scores ${GITHUB_REPOSITORY} > scores.json
        SOURCECRED_GITHUB_TOKEN=${TOKEN} docker run -i -e SOURCECRED_GITHUB_TOKEN sourcecred/widgets < scores.json > contributors.svg
        cat contributors.svg
    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: "master"
      run: |
        printf "GitHub Actor: ${GITHUB_ACTOR}\n"
        export BRANCH_FROM="update/contributors-graphic-$(date '+%Y-%m-%d')"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch
        git checkout -b "${BRANCH_FROM}" || git checkout "${BRANCH_FROM}"
        git branch

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git add contributors.svg

        if git diff-index --quiet HEAD --; then
           printf "No changes\n"
        else
           printf "Changes\n"
           git commit -m "Automated deployment to update contributors.svg $(date '+%Y-%m-%d')"
           git push origin "${BRANCH_FROM}"
        fi
        echo "::set-env name=PULL_REQUEST_FROM_BRANCH::${BRANCH_FROM}"

    - name: Open Pull Request
      uses: vsoch/pull-request-action@1.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "master"
